fintech_banking:
  target: ci

  outputs:
    ci:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: fintech_banking
      schema: analytics
      threads: 4